<?php
 return array (
  'titulo' => '<h3>Configuraciones generales <br> <small style="color: red;"> Si no está completamente seguro, no modifique ningún valor de este formulario. Consulte con el administrador del sistema. </small></h3>',
  'numero_territorial' => '220',
  'resolucion_habilitacion' => '0019',
  'anio_creacion_empresa' => '02',
  'bloqueado_x_contratos' => '8',
  'color_emp_label' => '#000066',
  'slogan' => 'SEGURIDAD Y COMODIDAD EN CADA VIAJE',
  'color_slogan' => '#cc9900',
  'texto_en_representacion_de' => 'PARA UN GRUPO ESPECIFICO DE USUARIOS DE TRANSPORTE DE PERSONAL (TRANSPORTE PARTICULAR)',
  'logo_min_transporte' => 'solo_transporte',
  'url_imagen_sello_empresa' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwHEfWwg4poY-npEz6zQX8rbpsJ-bDWElXhQ&usqp=CAU',
  'url_imagen_firma_rep_legal' => 'https://c0.klipartz.com/pngpicture/210/481/gratis-png-facsimil-firma-texto-sello-sello-de-goma.png',
  'url_imagen_sello_icontec' => 'https://d1yjjnpx0p53s8.cloudfront.net/styles/logo-thumbnail/s3/022014/untitled-1_61.png',
  'url_imagen_firma_y_sello_empresa' => 'https://c0.klipartz.com/pngpicture/210/481/gratis-png-facsimil-firma-texto-sello-sello-de-goma.png',
  'permitir_ingreso_contrato_en_mes_distinto_al_actual' => '1',
  'bloquear_ingreso_fecha_final_planilla_en_mes_siguiente' => '1',
  'mostrar_fechas_fuec_en_create_contratos' => '1',
  'url_id_modelo' => '0',
) ;