<?php
 return array (
  'titulo' => '<h3>Configuraciones generales <br> <small style="color: red;"> Si no está completamente seguro, no modifique ningún valor de este formulario. Consulte con el administrador del sistema. </small></h3>',
  'transaction_type_id_default' => '9',
  'document_type_id_default' => '15',
  'contact_id_default' => '1',
  'cta_cartera_default' => '27',
  'cta_anticipo_clientes_default' => '219',
  'cta_por_pagar_default' => '131',
  'cta_anticipo_proveedores_default' => '29',
  'cta_ingresos_default' => '230',
  'cta_gastos_default' => '359',
  'cta_impuestos_default' => '182',
  'cta_inventarios_default' => '73',
  'transaccion_default_cierre_ejercicio' => '9',
  'tipo_documento_cierre_ejercicio' => '43',
  'tercero_default_cierre_ejercicio' => '173',
  'cuenta_ganancias_perdidas_ejercicio' => '228',
  'url_id_modelo' => '0',
) ;