<?php
 return array (
  'titulo' => '<h3>Configuraciones generales <br> <small style="color: red;"> Si no está completamente seguro, no modifique ningún valor de este formulario. Consulte con el administrador del sistema. </small></h3>',
  'proveedor_tecnologico_default' => 'DATAICO',
  'fe_ambiente' => 'PRODUCCION',
  'enviar_email_clientes' => 'true',
  'email_copia_factura' => 'adalberto-77@hotmail.com',
  'WSDL' => 'https://api.dataico.com/direct/dataico_api/v2/invoices',
  'url_notas_credito' => 'https://api.dataico.com/direct/dataico_api/v2/credit_notes',
  'url_notas_debito' => 'https://api.dataico.com/direct/dataico_api/v2/debit_notes',
  'WSANEXO' => '',
  'url_documento_soporte' => 'https://api.dataico.com/direct/dataico_api/v2/support_docs',
  'WSREPORTES' => '',
  'tokenEmpresa' => '01811c21-b104-8552-93da-57821c86e3db',
  'tokenPassword' => '4facc5070884f0e15d9dc05c3ee4fb6b',
  'modalidad_asignada' => '2',
  'cantidadDecimales' => '4',
  'transaction_type_id_default' => '52',
  'document_type_id_default' => '47',
  'url_id_modelo' => '0',
) ;