<?php
 return array (
  'titulo' => '<h3>Configuraciones generales <br> <small style="color: red;"> Si no está completamente seguro, no modifique ningún valor de este formulario. Consulte con el administrador del sistema. </small></h3>',
  'proveedor_tecnologico_default' => 'DATAICO',
  'fe_ambiente' => 'PRUEBAS',
  'enviar_email_clientes' => 'true',
  'email_copia_factura' => 'adalberto-77@hotmail.com',
  'WSDL' => 'https://api.dataico.com/direct/dataico_api/v2/invoices',
  'url_notas_credito' => 'https://api.dataico.com/direct/dataico_api/v2/credit_notes',
  'url_notas_debito' => 'https://api.dataico.com/direct/dataico_api/v2/debit_notes',
  'WSANEXO' => '',
  'WSREPORTES' => '',
  'tokenEmpresa' => '002979c5-7c23-43ab-aa98-3fa7dce6e4d0',
  'tokenPassword' => 'a4afb1e20e856e8fb031b487efbfd239',
  'modalidad_asignada' => '2',
  'cantidadDecimales' => '4',
  'transaction_type_id_default' => '52',
  'document_type_id_default' => '47',
  'url_id_modelo' => '0',
) ;