<?php
 return array (
  'titulo' => '',
  'item_impuesto_id' => '1',
  'item_lista_precios_id' => '1',
  'item_bodega_principal_id' => '1',
  'fecha_inicio_calculo_costo_promedio' => '2022-02-02',
  'maneja_costo_promedio_por_bodegas' => '0',
  'core_tipo_transaccion_id' => '4',
  'core_tipo_doc_app_id' => '9',
  'core_tercero_id' => '212',
  'motivo_salida_id' => '3',
  'motivo_entrada_id' => '4',
  'ea_tipo_transaccion_id' => '1',
  'ea_tipo_doc_app_id' => '2',
  'ea_tercero_id' => '211',
  'ea_motivo_id' => '1',
  'motivo_salida_id_ot' => '5',
  'longitud_item' => '5',
  'longitud_talla' => '2',
  'longitud_color' => '0',
  'caracter_relleno' => '0',
  'ancho_hoja_impresion' => '295',
  'alto_hoja_impresion' => '',
  'url_id_modelo' => '0',
) ;