<?php
 return array (
  'titulo' => '<h3>Configuraciones generales <br> <small style="color: red;"> Si no está completamente seguro, no modifique ningún valor de este formulario. Consulte con el administrador del sistema. </small></h3>',
  'modo_visualizacion_nombre_completo_estudiante' => 'nombres_apellidos',
  'convenciones_valoraciones_aspectos' => '2',
  'formato_impresion_observador' => '2',
  'manejar_control_disciplinario' => '0',
  'manejar_matriz_dofa' => '1',
  'inv_producto_id_default_matricula' => '',
  'inv_producto_id_default_pension' => '',
  'transaccion_id_factura_estudiante' => '23',
  'modelo_id_factura_estudiante' => '234',
  'cantidad_facturas_vencidas_permitidas' => '2',
  'mostrar_password_en_ficha_matricula' => '1',
  'largo_consecutivo_codigo_matricula' => '3',
  'banner_reportes' => 'renderizado',
  'url_imagen_banner' => 'http://localhost/appsiel_2020./nube/banner-col-santa-teresitajpg.jpg',
  'etiqueta_datos_aspirante' => 'DATOS DEL ASPIRANTE',
  'mensaje_inscripcion_creada' => 'GRACIAS. Su inscripción ha sido registrada correctamente. Pronto nos comunicaremos con usted.',
  'url_id_modelo' => '0',
) ;