<?php
 return array (
  'titulo' => '<h3>Configuraciones generales <br> <small style="color: red;"> Si no está completamente seguro, no modifique ningún valor de este formulario. Consulte con el administrador del sistema. </small></h3>',
  'SMMLV' => '908526',
  'horas_laborales' => '240',
  'horas_dia_laboral' => '8',
  'valor_uvt_actual' => '36308',
  'sabado_es_dia_habil' => '1',
  'calcular_valor_proyectado_fondo_solidaridad' => '1',
  'concepto_salario_integral' => '2',
  'concepto_salud_obligatoria' => '64',
  'pago_salario_completo_en_incapacidades' => '0',
  'id_concepto_pagar_empresa_en_incapacidades' => '',
  'concepto_vacaciones_dias_no_habiles' => '',
  'dias_calendario_por_dia_vacacion_legal' => '24.33',
  'agrupacion_calculo_ibc_salud' => '8',
  'agrupacion_calculo_ibc_parafiscales' => '7',
  'concepto_a_pagar_pasante_sena' => '77',
  'porcentaje_liquidacon_pasante_sena' => '75',
  'cuenta_id_salarios_por_pagar' => '206',
  'tercero_id_salarios_por_pagar' => '',
  'proveedor_tecnologico_default' => 'DATAICO',
  'nom_elec_ambiente' => 'PRUEBAS',
  'pin_software' => '4123412',
  'enviar_email_empleados' => 'true',
  'email_copia_documento_soporte' => '',
  'url_servicio_emision' => 'https://api.dataico.com/direct/payroll-api/payroll-entries',
  'url_nota_ajuste_reemplazo' => 'https://api.dataico.com/direct/payroll-api/payroll-replacements',
  'url_nota_ajuste_eliminacion' => 'https://api.dataico.com/direct/payroll-api/payroll-deletions',
  'tokenEmpresa' => '39cfcc4f-946b-44b4-a281-5662460615d9',
  'tokenDian' => 'd0e88268-a4ab-447d-918c-19c1c248b5c3',
  'modalidad_asignada' => '2',
  'url_id_modelo' => '0',
) ;