<?php
 return array (
  'titulo' => '<h3>Configuraciones generales <br> <small style="color: red;"> Si no está completamente seguro, no modifique ningún valor de este formulario. Consulte con el administrador del sistema. </small></h3>',
  'SMMLV' => '908526',
  'horas_laborales' => '240',
  'horas_dia_laboral' => '8',
  'valor_uvt_actual' => '36308',
  'sabado_es_dia_habil' => '1',
  'calcular_valor_proyectado_fondo_solidaridad' => '1',
  'concepto_salario_integral' => '',
  'concepto_salud_obligatoria' => '2',
  'pago_salario_completo_en_incapacidades' => '0',
  'id_concepto_pagar_empresa_en_incapacidades' => '',
  'concepto_vacaciones_dias_no_habiles' => '',
  'dias_calendario_por_dia_vacacion_legal' => '24.33',
  'agrupacion_calculo_ibc_salud' => '',
  'agrupacion_calculo_ibc_parafiscales' => '',
  'concepto_a_pagar_pasante_sena' => '',
  'porcentaje_liquidacon_pasante_sena' => '75',
  'cuenta_id_salarios_por_pagar' => '206',
  'tercero_id_salarios_por_pagar' => '212',
  'url_id_modelo' => '0',
) ;