<?php
 return array (
  'titulo' => '<h3>Configuraciones generales <br> <small style="color: red;"> Si no está completamente seguro, no modifique ningún valor de este formulario. Consulte con el administrador del sistema. </small></h3>',
  'lista_precios_id' => '1',
  'lista_descuentos_id' => '1',
  'clase_cliente_id' => '1',
  'vendedor_id' => '1',
  'inv_bodega_id' => '1',
  'zona_id' => '1',
  'condicion_pago_id' => '1',
  'etiqueta_impuesto_principal' => 'INC',
  'factura_ventas_modelo_id' => '139',
  'factura_ventas_tipo_transaccion_id' => '23',
  'factura_ventas_tipo_doc_app_id' => '18',
  'longitud_consecutivo_factura' => '8',
  'rm_modelo_id' => '164',
  'rm_tipo_transaccion_id' => '24',
  'rm_tipo_doc_app_id' => '7',
  'dvc_modelo_id' => '174',
  'dvc_tipo_transaccion_id' => '34',
  'dvc_tipo_doc_app_id' => '35',
  'pv_modelo_id' => '175',
  'pv_tipo_transaccion_id' => '42',
  'pv_tipo_doc_app_id' => '41',
  'modo_liquidacion_precio' => 'lista_de_precios',
  'permitir_venta_menor_costo' => '0',
  'permitir_inventarios_negativos' => '1',
  'detallar_iva_cotizaciones' => '1',
  'detallar_condicion_ventas' => '1',
  'encabezado_linea_1' => 'SERVIMOS CON CALIDAD',
  'encabezado_linea_2' => '',
  'encabezado_linea_3' => '',
  'pie_pagina_linea_1' => 'GRACIAS POR SU COMPRA.',
  'pie_pagina_linea_2' => '',
  'pie_pagina_linea_3' => '',
  'url_id_modelo' => '0',
) ;