<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class CorePaisesGentilicioSeeder extends Seeder
{
    public function run()
    {
        if (!Schema::hasTable('core_paises') || !Schema::hasColumn('core_paises', 'gentilicio')) {
            return;
        }

        foreach ($this->rows() as $row) {
            $updated = DB::table('core_paises')
                ->where('id', $row['codigo'])
                ->update(array('gentilicio' => $row['gentilicio']));

            if ($updated > 0) {
                continue;
            }

            DB::table('core_paises')
                ->whereRaw('UPPER(descripcion) = ?', array($this->normalize($row['nombre'])))
                ->update(array('gentilicio' => $row['gentilicio']));
        }
    }

    private function normalize($value)
    {
        return trim(strtoupper($value));
    }

    private function rows()
    {
        $csv = '13;AFGANISTAN;AFGANA
384;ÅLAND;FINLANDESA
17;ALBANIA;ALBANESA
23;ALEMANIA;ALEMANA
37;ANDORRA;ANDORRANA
40;ANGOLA;ANGOLESA
895;ANGUILA;BRITANICO
143;ANTARTIDA;ANTÁRTIDA
43;ANTIGUA Y BARBUDA;ANTIGUANA
921;ANTILLAS HOLANDESAS;HOLANDESA
44;ANTILLAS NEERLANDESAS;HOLANDESA
55;ARABIA SAUDITA;SAUDITA
59;ARGELIA;ARGELINA
63;ARGENTINA;ARGENTINA
65;ARMENIA;ARMENIA
67;ARUBA;HOLANDESA
448;ARY MACEDONIA;MACEDONIA
69;AUSTRALIA;AUSTRALIANA
72;AUSTRIA;AUSTRIACA
75;AZERBAIYAN;AZERBAIYANA
77;BAHAMAS;BAHAMEÑA
80;BAHREIN;BAHRENITA
81;BANGLADESH;BENGALESA
83;BARBADOS;BARBADIANA
87;BELGICA;BELGA
88;BELICE;BELICEÑA
89;BENIN;BENINESA
90;BERMUDAS;BRITANICA
85;BIELORRUSIA;BIELORRUSA
97;BOLIVIA;BOLIVIANA
99;BOSNIA;BOSNIA
101;BOTSWANA;BETCHUANA
105;BRASIL;BRASILEÑA
108;BRUNEI;BRUENANA
111;BULGARIA;BULGARA
113;BURKINA FASO;BURKINESA
115;BURUNDI;BURUNDINESA
117;BUTAN;BHUTANESA
127;CABO VERDE;CABOVERDIANA
141;CAMBOYA;CAMBOYANA
145;CAMERUN;CAMERUNENSE
149;CANADA;CANADIENSE
151;CHAD;CHADIANA
211;CHILE;CHILENA
215;CHINA;CHINA
221;CHIPRE;CHIPRIOTA
717;CIUDAD DEL VATICANO;SANTA SEDE
169;COLOMBIA;COLOMBIANA
171;COMORAS;COMORANA
651;COREA DEL NORTE;NORCOREANA
190;COREA DEL SUR;COREANA
193;COSTA DE MARFIL;MARFILENSE
196;COSTA RICA;COSTARRICENSE
198;CROACIA;CROATA
199;CUBA;CUBANA
201;CURAZAO;HOLANDESA
232;DINAMARCA;DANESA
235;DOMINICA;DOMINICA
239;ECUADOR;ECUATORIANA
240;EGIPTO;EGIPCIA
242;EL SALVADOR;SALVADOREÑA
244;EMIRATOS ARABES UNIDOS;ARABE
246;ERITREA;ERITREA
247;ESLOVAQUIA;ESLOVACA
248;ESLOVENIA;ESLOVENIA
245;ESPAÑA;ESPAÑOLA
249;ESTADOS UNIDOS;ESTADOUNIDENSE
251;ESTONIA;ESTONIA
253;ETIOPIA;ETIOPE
267;FILIPINAS;FILIPINA
271;FINLANDIA;FINLANDESA
255;FIYI;FIJIANA
275;FRANCIA;FRANCESA
281;GABON;GABONESA
285;GAMBIA;GAMBIANA
287;GEORGIA;GEORGIANA
289;GHANA;GHANESA
293;GIBRALTAR;BRITANICA
297;GRANADA;GRANADINA
301;GRECIA;GRIEGA
315;GROENLANDIA;DANESA
338;GUADALUPE;FRANCESA
339;GUAM;ESTADOUNIDENSE
317;GUATEMALA;GUATEMALTECA
340;GUAYANA FRANCESA;FRANCESA
146;GUERNSEY;GUERNSEY
329;GUINEA;GUINEA
331;GUINEA ECUATORIAL;ECUATOGUINEANA
334;GUINEA-BISSAU;GUINEANA
325;GUYANA;GUYANESA
341;HAITI;HAITIANA
345;HONDURAS;HONDUREÑA
347;HONG KONG;CHINA
355;HUNGRIA;HUNGARA
361;INDIA;INDIA
365;INDONESIA;INDONESIA
980;INTERPOL;SIN
372;IRAN;IRANI
369;IRAQ;IRAQUI
375;IRLANDA;IRLANDESA
173;ISLA BOUVET;ISLA BOUVET
380;ISLA DE MAN;BRITANICA
387;ISLA DE NAVIDAD;AUSTRALIANA
379;ISLANDIA;ISLANDESA
137;ISLAS CAIMAN;BRITANICA
178;ISLAS COCOS;ISLAS COCOS
388;ISLAS COOK;NEOZELANDESA
390;ISLAS FEROE;DANESA
186;ISLAS HEARD Y MCDONALD;ISLAS HEARD Y MCDONALD
191;ISLAS MALVINAS;ISLAS MALVINAS
392;ISLAS MARIANAS DEL NORTE;ESTODOUNIDENSE
475;ISLAS MARSHALL;MARSHALLINA
381;ISLAS PITCAIRN;BRITANICA
395;ISLAS SALOMON;SALOMONICA
900;ISLAS TURCAS Y CAICOS;BRITANICA
200;ISLAS ULTRAMARINAS DE ESTADOS UNIDOS;ISLAS ULTRAMARINAS DE ESTADOS UNIDOS
866;ISLAS VIRGENES BRITANICAS;BRITANICA
867;ISLAS VIRGENES ESTADOUNIDENSES;ESTADOUNIDENSE
383;ISRAEL;ISRAELI
386;ITALIA;ITALIANA
391;JAMAICA;JAMAIQUINA
399;JAPON;JAPONESA
160;JERSEY;JERSEY
403;JORDANIA;JORDANA
406;KAZAJISTAN;KAZAQUI
410;KENIA;KENYANA
412;KIRGUISTAN;KIRGUENSE
411;KIRIBATI;KIRIBATI
414;KOSOVO;KOSOVO
413;KUWAIT;KUWAITI
420;LAOS;LAOSEANA
426;LESOTHO;LESOTHA
428;LETONIA;LETONA
431;LIBANO;LIBANESA
434;LIBERIA;LIBERIANA
438;LIBIA;LIBANES
441;LIECHTENSTEIN;LIECHTENSTEIN
429;LITUANIA;LITUANA
442;LUXEMBURGO;LUXEMBURGUES
447;MACAO;CHINA
450;MADAGASCAR;MALGACHE
455;MALASIA;MALAYA
458;MALAWI;MALAWI
461;MALDIVAS;MALDIVIA
464;MALI;MALINESA
467;MALTA;MALTESA
474;MARRUECOS;MARROQUI
490;MARTINICA;FRANCESA
485;MAURICIO;MAURICIANA
488;MAURITANIA;MAURITANA
494;MAYOTTE;FRANCESA
493;MEXICO;MEXICANA
503;MICRONESIA;MICRONESIA
495;MOLDAVIA;MOLDAVA
496;MONACO;MONEGASCA
497;MONGOLIA;MONGOL
499;MONTENEGRO;MONTENEGRO
501;MONTSERRAT;BRITANICA
505;MOZAMBIQUE;MOZAMBIQUEÑA
507;MYANMAR;BIRMANA
981;NACIONES UNIDAS;SIN
512;NAMIBIA;NAMIBIA
508;NAURU;NAURUANA
517;NEPAL;NEPALESA
521;NICARAGUA;NICARAGUENSE
528;NIGER;NIGERINA
525;NIGERIA;NIGERIANA
531;NIUE;NEOZELANDESA
0;NO APLICA;NO APLICA
163;NORFOLK;NORFOLK
538;NORUEGA;NORUEGA
539;NUEVA CALEDONIA;FRANCESA
540;NUEVA ZELANDA;NEOZELANDESA
542;OMAN;OMANI
573;PAISES BAJOS;HOLANDESA
576;PAKISTAN;PAKISTANI
578;PALAOS;PALAUENSE
600;PALESTINA (ANP);PALESTINA
580;PANAMA;PANAMEÑA
582;PAPUA NUEVA GUINEA;PAPUES
586;PARAGUAY;PARAGUAYA
589;PERU;PERUANA
609;POLINESIA FRANCESA;FRANCESA
603;POLONIA;POLACA
607;PORTUGAL;PORTUGUESA
611;PUERTO RICO;ESTADOUNIDENSE
618;QATAR;QATARIANA
628;REINO UNIDO;BRITANICA
998;REPUBLICA CENTROAFRICANA;CENTROAFRICANO
207;REPUBLICA CHECA;CHECA
642;REPUBLICA DE MACEDONIA;MACEDONIO
170;REPUBLICA DEL CONGO;REPUBLICA DEL CONGO
177;REPUBLICA DEMOCRATICA DEL CONGO;CONGOLESA
647;REPUBLICA DOMINICANA;DOMINICANA
650;REUNION;FRANCESA
670;RUMANIA;RUMANA
673;RUSIA;RUSA
675;RWANDA;RWANDESA
680;SAHARA OCCIDENTAL;MARROQUI
699;SAMOA;SAMOANA
698;SAMOA AMERICANA;ESTADOUNIDENSE
695;SAN CRISTOBAL Y NIEVES;SANCRISTOBALENSE
701;SAN MARINO;SANMARINENSE
682;SAN PEDRO Y MIQUELON;FRANCESA
705;SAN VICENTE Y LAS GRANADINAS;SANVICENTINA
708;SANTA HELENA;BRITANICA
715;SANTA LUCIA;SANTALUCENSE
720;SANTO TOME Y PRINCIPE;SANTOTOMENSE
728;SENEGAL;SENEGALESA
729;SERBIA;SERBIA
731;SEYCHELLES;SEYCHELLESA
735;SIERRA LEONA;LEONESA
741;SINGAPUR;SINGAPURIANA
744;SIRIA;SIRIA
748;SOMALIA;SOMALI
750;SRI LANKA;CINGALESA
756;SUDAFRICA;SUDAFRICANA
759;SUDAN;SUDANESA
764;SUECIA;SUECA
767;SUIZA;SUIZA
770;SURINAM;SURINAMESA
730;SVALBARD Y JAN MAYEN;NORUEGA
773;SWAZILANDIA;SWAZI
776;TAILANDIA;TAILANDESA
774;TAIWAN;TAIWANESA
780;TANZANIA;TANZANIA
775;TAYIKISTAN;TAYIKISTANI
779;TERRITORIO BRITANICO DEL OCEANO INDICO;BRITANICA
781;TERRITORIOS AUSTRALES FRANCESES;FRANCESA
783;TIMOR ORIENTAL;INDONESIA
800;TOGO;TOGOLESA
812;TOKELAU;NEOZELANDESA
810;TONGA;TONGANESA
815;TRINIDAD Y TOBAGO;TRINITARIA
820;TUNEZ;TUNECINA
829;TURKMENISTAN;TURCOMANA
827;TURQUIA;TURCA
828;TUVALU;TUVALUANA
830;UCRANIA;UCRANIANA
833;UGANDA;UGANDESA
845;URUGUAY;URUGUAYA
847;UZBEKISTAN;UZBEQUI
849;VANUATU;VANUATUENSE
850;VENEZUELA;VENEZOLANA
855;VIETNAM;VIETNAMITA
394;WALLIS Y FUTUNA;FRANCESA
880;YEMEN;YEMENITA
920;YIBUTI;SIN
890;ZAMBIA;ZAMBIANA
892;ZIMBABUE;ZIMBABWUANA';

        $rows = array();
        foreach (explode("\n", $csv) as $line) {
            $columns = str_getcsv(trim($line), ';');
            if (count($columns) < 3) {
                continue;
            }

            $rows[] = array(
                'codigo' => (int)$columns[0],
                'nombre' => $columns[1],
                'gentilicio' => $columns[2],
            );
        }

        return $rows;
    }
}
