@if($footer!=null)
<style>
    <?php
    switch ($footer->animacion) {
        case 'circulos-descienden':
            echo ".footerarea {
        position: relative;
        overflow: hidden;
        display: flex;
        justify-content: center;
        align-content: center;

        &__content {
            position: relative;
            align-self: center;
            padding: 3rem 0;
        }
    }
    .snow {
        position: absolute;
        min-width: 100vw;
        min-height: 100vh;
        height: 100%;
        width: 100%;
        top: 0;
        left: 0;
    }

    .snow .svg {
        position: absolute;
        width: 100%;
        height: 100%;
    }

    #snow-top-layer {
        will-change: transform;
        transform: translateY(-768px);
        animation: fall 22.5s infinite linear;
    }

    #snow-bottom-layer {
        will-change: transform;
        transform: translateY(-768px);
        animation: fall 45s infinite linear;
    }

    @keyframes fall {

        100% {
            transform: translateY(0);
        }

    }";
            break;
        case 'ninguna':
            echo ".footerarea {
        position: relative;
    }";
            break;
    }
    ?>.footerarea img {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
    }

    @media (max-width: 468px) {
        .footerarea {
            background-color: <?php echo $footer->background; ?>;
        }

        .footerarea img {
            display: none;
        }
    }

    .footer-font {
        font-family: <?php echo $footer->configuracionfuente->fuente->font; ?> !important;
    }
</style>

<!-- <div class="footerarea" style="padding-top: 20px; background: linear-gradient(180deg, rgba(255,255,255,1) 0%, { {$footer->background}} 100%); color: { {$footer->color}}"> -->

<!-- Generated by https://smooth.ie/blogs/news/svg-wavey-transitions-between-sections -->


@if($footer->ondas=='SI')
<div style="height: 150px; overflow: hidden;">
    <svg viewBox="0 0 500 150" preserveAspectRatio="none" style="height: 100%; width: 100%;">
        <path d="M0.00,49.98 C149.99,150.00 349.20,-49.98 500.00,49.98 L500.00,150.00 L0.00,150.00 Z" style="stroke: none; fill: {{$footer->background}};"></path>
    </svg>
</div>
@endif

<div class="footer-font footerarea @if($footer->animacion=='efecto-ondas-cursor') efecto-ondas-cursor @endif" style="padding-top: 20px; background: {{$footer->background}}; color: {{$footer->color}}; overflow: hidden;">
    <div class="container footer-font">
        <?php
        switch ($footer->animacion) {
            case 'circulos-descienden':
        ?>
                <div class="snow">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1536" preserveAspectRatio="xMidYMax slice">
                        <g fill="#FFF" fill-opacity=".15" transform="translate(55 42)">
                            <g id="snow-bottom-layer">
                                <ellipse cx="6" cy="1009.5" rx="6" ry="5.5" />
                                <ellipse cx="138" cy="1110.5" rx="6" ry="5.5" />
                                <ellipse cx="398" cy="1055.5" rx="6" ry="5.5" />
                                <ellipse cx="719" cy="1284.5" rx="6" ry="5.5" />
                                <ellipse cx="760" cy="1155.5" rx="6" ry="5.5" />
                                <ellipse cx="635" cy="1459.5" rx="6" ry="5.5" />
                                <ellipse cx="478" cy="1335.5" rx="6" ry="5.5" />
                                <ellipse cx="322" cy="1414.5" rx="6" ry="5.5" />
                                <ellipse cx="247" cy="1234.5" rx="6" ry="5.5" />
                                <ellipse cx="154" cy="1425.5" rx="6" ry="5.5" />
                                <ellipse cx="731" cy="773.5" rx="6" ry="5.5" />
                                <ellipse cx="599" cy="874.5" rx="6" ry="5.5" />
                                <ellipse cx="339" cy="819.5" rx="6" ry="5.5" />
                                <ellipse cx="239" cy="1004.5" rx="6" ry="5.5" />
                                <ellipse cx="113" cy="863.5" rx="6" ry="5.5" />
                                <ellipse cx="102" cy="1223.5" rx="6" ry="5.5" />
                                <ellipse cx="395" cy="1155.5" rx="6" ry="5.5" />
                                <ellipse cx="826" cy="943.5" rx="6" ry="5.5" />
                                <ellipse cx="626" cy="1054.5" rx="6" ry="5.5" />
                                <ellipse cx="887" cy="1366.5" rx="6" ry="5.5" />
                                <ellipse cx="6" cy="241.5" rx="6" ry="5.5" />
                                <ellipse cx="138" cy="342.5" rx="6" ry="5.5" />
                                <ellipse cx="398" cy="287.5" rx="6" ry="5.5" />
                                <ellipse cx="719" cy="516.5" rx="6" ry="5.5" />
                                <ellipse cx="760" cy="387.5" rx="6" ry="5.5" />
                                <ellipse cx="635" cy="691.5" rx="6" ry="5.5" />
                                <ellipse cx="478" cy="567.5" rx="6" ry="5.5" />
                                <ellipse cx="322" cy="646.5" rx="6" ry="5.5" />
                                <ellipse cx="247" cy="466.5" rx="6" ry="5.5" />
                                <ellipse cx="154" cy="657.5" rx="6" ry="5.5" />
                                <ellipse cx="731" cy="5.5" rx="6" ry="5.5" />
                                <ellipse cx="599" cy="106.5" rx="6" ry="5.5" />
                                <ellipse cx="339" cy="51.5" rx="6" ry="5.5" />
                                <ellipse cx="239" cy="236.5" rx="6" ry="5.5" />
                                <ellipse cx="113" cy="95.5" rx="6" ry="5.5" />
                                <ellipse cx="102" cy="455.5" rx="6" ry="5.5" />
                                <ellipse cx="395" cy="387.5" rx="6" ry="5.5" />
                                <ellipse cx="826" cy="175.5" rx="6" ry="5.5" />
                                <ellipse cx="626" cy="286.5" rx="6" ry="5.5" />
                                <ellipse cx="887" cy="598.5" rx="6" ry="5.5" />
                            </g>
                        </g>
                        <g fill="#FFF" fill-opacity=".3" transform="translate(65 63)">
                            <g id="snow-top-layer">
                                <circle cx="8" cy="776" r="8" />
                                <circle cx="189" cy="925" r="8" />
                                <circle cx="548" cy="844" r="8" />
                                <circle cx="685" cy="1115" r="8" />
                                <circle cx="858" cy="909" r="8" />
                                <circle cx="874" cy="1438" r="8" transform="rotate(180 874 1438)" />
                                <circle cx="657" cy="1256" r="8" transform="rotate(180 657 1256)" />
                                <circle cx="443" cy="1372" r="8" transform="rotate(180 443 1372)" />
                                <circle cx="339" cy="1107" r="8" transform="rotate(180 339 1107)" />
                                <circle cx="24" cy="1305" r="8" transform="rotate(180 24 1305)" />
                                <circle cx="8" cy="8" r="8" />
                                <circle cx="189" cy="157" r="8" />
                                <circle cx="548" cy="76" r="8" />
                                <circle cx="685" cy="347" r="8" />
                                <circle cx="858" cy="141" r="8" />
                                <circle cx="874" cy="670" r="8" transform="rotate(180 874 670)" />
                                <circle cx="657" cy="488" r="8" transform="rotate(180 657 488)" />
                                <circle cx="443" cy="604" r="8" transform="rotate(180 443 604)" />
                                <circle cx="339" cy="339" r="8" transform="rotate(180 339 339)" />
                                <circle cx="24" cy="537" r="8" transform="rotate(180 24 537)" />
                            </g>
                        </g>
                    </svg>
                </div>
        <?php
                break;
        }
        ?>
        <div class="row footer-font">
            @if($footer->ubicacion == '')
            @if($contactenos == null)
            <div class="col-md-12 col-sm-12 d-flex  flex-wrap">
                @foreach($footer->categorias as $item)
                <div class="contenido col-md-4 col-sm-12" style="margin-top: 20px">
                    <h5 class="column-title footer-font" style="color: {{$footer->color}}; font-size: 20px; font-weight: bold;">{{$item->texto}}</h5>
                    <aside class="">
                        <ul id="menu-menu4" class="menu">
                            @foreach($item->enlaces as $enlace)
                            <li id="" class="footer-font" style="list-style: none; margin-top: 10px; text-align: ;"><a class="footer-font" style="color: {{$footer->color}}; font-size: 14px;" href="{{$enlace->enlace}}" target="_blank"><i class="fa fa-{{$enlace->icono}}"></i> {{' '.$enlace->texto}}
                                </a>
                            </li>
                            @endforeach
                        </ul>
                    </aside>
                </div>
                <!--end .widget-column-2-->
                @endforeach
            </div>
            @else
            <div class="col-md-9 col-sm-12 d-flex justify-content-between flex-wrap">
                @foreach($footer->categorias as $item)
                <div class="contenido col-md-6 col-sm-12" style="margin-top: 20px">
                    <h5 class="column-title footer-font" style="color: {{$footer->color}}; font-size: 20px; font-weight: bold;">{{$item->texto}}</h5>
                    <aside class="">
                        <ul id="menu-menu4" class="menu">
                            @foreach($item->enlaces as $enlace)
                            <li id="" class="footer-font" style="list-style: none; margin-top: 10px;"><a class="footer-font" style="color: {{$footer->color}}; font-size: 14px" target="_blank" href="{{$enlace->enlace}}"><i class="fa fa-{{$enlace->icono}}"></i> {{' '.$enlace->texto}}
                                </a>
                            </li>
                            @endforeach
                        </ul>
                    </aside>
                </div>
                <!--end .widget-column-2-->
                @endforeach
            </div>
            <div class="col-md-3 col-sm-12 d-flex justify-content-between flex-wrap">
                <div class="contenido col-md-12 col-sm-12" style="margin:20px 0;">
                    <h5 class="column-title footer-font" style="color: {{$footer->color}}; font-size: 20px; font-weight: bold;">
                        CONTACTENOS</h5>
                    <aside class="">
                        {{Form::contactenos($contactenos)}}
                    </aside>
                </div>
                <!--end .widget-column-2-->
            </div>
            @endif
            @else
            @if($contactenos == null)
            <div class="col-md-9 col-sm-12 d-flex  flex-wrap">
                @foreach($footer->categorias as $item)
                <div class="contenido col-md-4 col-sm-12" style="margin-top: 20px">
                    <h5 class="column-title footer-font" style="color: {{$footer->color}}; font-size: 20px; font-weight: bold;">{{$item->texto}}</h5>
                    <aside class="">
                        <ul id="menu-menu4" class="menu">
                            @foreach($item->enlaces as $enlace)
                            <li id="" class="footer-font" style="list-style: none; margin-top: 10px;"><a class="footer-font" style="color: {{$footer->color}}; font-size: 14px;" href="{{$enlace->enlace}}" target="_blank"><i class="fa fa-{{$enlace->icono}}"></i> {{' '.$enlace->texto}}
                                </a>
                            </li>
                            @endforeach
                        </ul>
                    </aside>
                </div>
                <!--end .widget-column-2-->
                @endforeach
            </div>
            <div class="col-md-3 col-sm-12 d-flex justify-content-between flex-wrap">
                <div class="contenido col-md-12 col-sm-12" style="margin:20px 0;">
                    <h5 class="column-title footer-font" style="color: {{$footer->color}}; font-size: 20px; font-weight: bold;">
                        ENCUENTRANOS</h5>
                    <aside class="footer-font">
                        {!! str_replace('width="300"','width="200"',$footer->ubicacion)!!}
                    </aside>
                </div>
                <!--end .widget-column-2-->
            </div>
            @else
            <div class="col-md-6 col-sm-12 d-flex justify-content-between flex-wrap">
                @foreach($footer->categorias as $item)
                <div class="contenido col-md-6 col-sm-12" style="margin-top: 20px">
                    <h5 class="column-title footer-font" style="color: {{$footer->color}}; font-size: 20px; font-weight: bold;">{{$item->texto}}</h5>
                    <aside class="">
                        <ul id="menu-menu4" class="menu">
                            @foreach($item->enlaces as $enlace)
                            <li id="" class="footer-font" style="list-style: none; margin-top: 10px;"><a class="footer-font" style="color: {{$footer->color}};" href="{{$enlace->enlace}}" target="_blank"><i class="fa fa-{{$enlace->icono}}"></i> {{' '.$enlace->texto}}
                                </a>
                            </li>
                            @endforeach
                        </ul>
                    </aside>
                </div>
                <!--end .widget-column-2-->
                @endforeach
            </div>
            <div class="col-md-6 col-sm-12 d-flex justify-content-between flex-wrap">
                <div class="contenido col-md-6 col-sm-12" style="margin:20px 0;">
                    <h5 class="column-title footer-font" style="color: {{$footer->color}}; font-size: 20px; font-weight: bold;">
                        CONTACTENOS</h5>
                    <aside class="footer-font">
                        {{Form::contactenos($contactenos)}}
                    </aside>
                </div>
                <!--end .widget-column-2-->
                <div class="contenido col-md-6 col-sm-12" style="margin:20px 0;">
                    <h5 class="column-title footer-font" style="color: {{$footer->color}}; font-size: 20px; font-weight: bold;">
                        ENCUENTRANOS</h5>
                    <aside class="footer-font">
                        {!! str_replace('width="300"','width="200"',$footer->ubicacion)!!}
                    </aside>
                </div>
                <!--end .widget-column-2-->
            </div>
            @endif
            @endif
        </div>
        <div class="row footer-font" style="background-color: {{$footer->background2}};">
            <div id="div1" class="col-md-12 col-sm-12 d-flex justify-content-between flex-wrap" style="margin-top: 20px; float: left;">
                <p class="footer-font" style="font-size: 15px; color: {{$footer->color}}; width: 80%; padding-left: 20px;">
                    &copy; {{$footer->texto.' '.$footer->copyright}}
                </p>
                <ul class="d-flex justify-content-between">
                    @foreach($redes as $red)
                    <li style="list-style: none; margin-right: 10px;">
                        <a class="footer-font" href="{{$red->enlace}}" style="color:{{$footer->color}}; font-size: 24px;" target="_blank"><i class="fa fa-{{$red->icono}}"></i></a>
                    </li>
                    @endforeach
                </ul>
            </div>
        </div>
    </div>
    <!--end .container-->

</div>

@else
<div class="section-header footer-font">
    <h2 class="section-title text-center wow fadeInDown">Sección</h2>
    <p class="text-center wow fadeInDown">Sin configuración</p>
</div>
@endif